option_settings:
  aws:elasticbeanstalk:application:environment:
    PORT: 5000
    ENV: dev
    POSTGRES_HOST: fwd-third-project-database.cefvcghup7xe.eu-central-1.rds.amazonaws.com
    POSTGRES_DB: postgres
    POSTGRES_USER: safwat
    POSTGRES_PASSWORD: BV02b4S5Yo6tC11glrJ4
    POSTGRES_HOST_DEV: 127.0.0.1
    POSTGRES_DB_DEV: store_api
    POSTGRES_USER_DEV: safwat
    POSTGRES_PASSWORD_DEV: password
    POSTGRES_DB_TEST: store_api_test
    BCRYPT_PASSWORD: 45w8sfgrk^%$sdsdww>,,,ld
    SALT_ROUNDS: 8
    JWT_SECRET: A-STORE-APP-secretToProtectTokens@3verYrequest